name: Philo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: Compilation & Tests & Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind gcc make python3 python3-pip jq
        pip install norminette

    - name: Run test pipeline (Python script)
      run: python3 .github/script/tester.py

    - name: Send CI report to Discord
      if: always()
      run: |
        content="**Philo CI:** Job terminé. Résumé :"
        body="$(tail -n 30 logs/report.txt)"
        payload=$(jq -n --arg content "$content" --arg body "$body" \
          '{content: "\($content)\n```\n\($body)\n```"}')
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "$payload" \
             https://discord.com/api/webhooks/1360602188866392156/PpaA3UHTS9ARn-iX8mPfCOEAnUNXqzmPmwVYH_Rp_7gusu2CXqQeaqx94_1DOeCErVFd