name: Philo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: Compilation & Tests & Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind gcc make python3 python3-pip
        pip install norminette

    - name: Run test pipeline (Python script)
      run: python3 .github/script/tester.py

    - name: Send email report
      uses: dawidd6/action-send-mail@v3
      if: always()
      with:
        server_address: mail.infomaniak.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Philosophers CI Report"
        to: ${{ secrets.EMAIL_USERNAME }}
        from: GitHub CI <${{ secrets.EMAIL_USERNAME }}>
        body: |
          $(cat logs/report.txt)